### ISSUE TITLE
Peer awareness

### ISSUE THREAD

**Issue by Syy0n** [ricardobaumann/spring_cloud_helloworld#7]
Hey Ricardo,

is there any way to run the registry in a peer aware mode with one docker image?
As long as i have to change the port and the serviceUrl of both peers, i see no other
possibilities to work with vm options or to build a second image...?

Is there any way to already scale a microservice in the compose.yml?

**Comment by ricardobaumann** [comment]
Hey Syyon. For your first question, yes it is possible, but its not a good practice. Docker suggests you to use a container for just one service/application, and link container together to build your solution. For your second question, scaling in docker-compose is done using the docker-compose scale command, and so far its not possible to do be done on compose.yml file, unfortunately. 

Thanks for your comment, and sorry for the delay. And let me know if I understood your questions.
